// @generated by protoc-gen-connect-web v0.3.2 with parameter "target=ts"
// @generated from file store/v1/store.proto (package store.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GreetRequest, GreetResponse } from "./store_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service store.v1.GreetService
 */
export const GreetService = {
  typeName: "store.v1.GreetService",
  methods: {
    /**
     * @generated from rpc store.v1.GreetService.Greet
     */
    greet: {
      name: "Greet",
      I: GreetRequest,
      O: GreetResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

